stages:
  - build
  - deploy

build:
    image: docker
    services:
        - docker:dind
    stage: build
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
        - docker build -t registry.gitlab.com/dygufa/sengram:v$CI_PIPELINE_ID .
        - docker push registry.gitlab.com/dygufa/sengram:v$CI_PIPELINE_ID

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - kubectl config set-cluster k8s --server="${SERVER}"
    - kubectl config set clusters.k8s.certificate-authority-data ${CERTIFICATE_AUTHORITY_DATA}
    - kubectl config set-credentials gitlab --token="${USER_TOKEN}"
    - kubectl config set-context default --cluster=k8s --user=gitlab
    - kubectl config use-context default
    - sed -i "s/\$TELEGRAM_CHAT_ID/${TELEGRAM_CHAT_ID}/g" deploy/app.yml
    - sed -i "s/\$TELEGRAM_BOT_TOKEN/${TELEGRAM_BOT_TOKEN}/g" deploy/app.yml
    - cat deploy/*.yml > tmp
    - kubectl apply -f tmp